In [1]:
import pandas as pd

In [2]:
df = pd.read_parquet('data/banco_carnes_un_v2_ed.parquet')

In [4]:
df.groupby(by=['codigo', 'has_change']).count()

                      ...1      ano       UF  municipio  dados.fornecedor  \
codigo has_change
1      0                90       90       90         90                90
11     0           2258621  2258621  2258621    2258621           2258621
12     0            261493   261493   261493     261493            261493
13     0             13398    13398    13398      13398             13398
14     0           1846912  1846912  1846912    1846912           1846912
15     0            360352   360352   360352     360352            360352
16     0            119340   119340   119340     119340            119340
17     0             23776    23776    23776      23776             23776
18     0             14173    14173    14173      14173             14173
21     0             57650    57650    57650      57650             57650
22     0            886284   886284   886284     886284            886284
23     0             11400    11400    11400      11400             11400
31     0            167124   167124   167124     167124            167124
32     0            207373   207373   207373     207373            207373
33     0              2258     2258     2258       2258              2258
34     0               734      734      734        734               734
41     0            746946   746946   746946     746946            746946
       1            397583   397583   397583     397583            397583
42     0               391      391      391        391               391
51     0            280349   280349   280349     280349            280349
53     0                11       11       11         11                11

                   dados.CNPJ.CPF  dados.tipo  dados.n_doc  dados.emissao  \
codigo has_change
1      0                       90          90           90             90
11     0                  2258621     2258621      2258621        2258621
12     0                   261493      261493       261493         261493
13     0                    13398       13398        13398          13398
14     0                  1846912     1846912      1846912        1846912
15     0                   360352      360352       360352         360352
16     0                   119340      119340       119340         119340
17     0                    23776       23776        23776          23776
18     0                    14173       14173        14173          14173
21     0                    57650       57650        57650          57650
22     0                   886284      886284       886284         886284
23     0                    11400       11400        11400          11400
31     0                   167124      167124       167124         167124
32     0                   207373      207373       207373         207373
33     0                     2258        2258         2258           2258
34     0                      734         734          734            734
41     0                   746946      746946       746946         746946
       1                   397583      397583       397583         397583
42     0                      391         391          391            391
51     0                   280349      280349       280349         280349
53     0                       11          11           11             11

                   valor_total_nota_fiscal  ...  valor_real  cluster  \
codigo has_change                           ...
1      0                                90  ...          90       90
11     0                           2258621  ...     2258621  2258621
12     0                            261493  ...      261493   261493
13     0                             13398  ...       13398    13398
14     0                           1846912  ...     1846912  1846912
15     0                            360352  ...      360352   360352
16     0                            119340  ...      119340   119340
17     0                             23776  ...       23776    23776
18     0                             14173  ...       14173    14173
21     0                             57650  ...       57650    57650
22     0                            886284  ...      886284   886284
23     0                             11400  ...       11400    11400
31     0                            167124  ...      167124   167124
32     0                            207373  ...      207373   207373
33     0                              2258  ...        2258     2258
34     0                               734  ...         734      734
41     0                            746946  ...      746946   746946
       1                            397583  ...      397583   397583
42     0                               391  ...         391      391
51     0                            280349  ...      280349   280349
53     0                                11  ...          11       11

                   valor_real_USD  produtos   un_adj  unit_kg  price_kg  \
codigo has_change
1      0                       90        90       90       90        90
11     0                  2258621   2258621  2258621  2258621   2258621
12     0                   261493    261493   261493   261493    261493
13     0                    13398     13398    13398    13398     13398
14     0                  1846912   1846912  1846912  1846912   1846912
15     0                   360352    360352   360352   360352    360352
16     0                   119340    119340   119340   119340    119340
17     0                    23776     23776    23776    23776     23776
18     0                    14173     14173    14173    14173     14173
21     0                    57650     57650    57650    57650     57650
22     0                   886284    886284   886284   886284    886284
23     0                    11400     11400    11400    11400     11400
31     0                   167124    167124   167124   167124    167124
32     0                   207373    207373   207373   207373    207373
33     0                     2258      2258     2258     2258      2258
34     0                      734       734      734      734       734
41     0                   746946    746946   746946   746946    746946
       1                   397583    397583   397583   397583    397583
42     0                      391       391      391      391       391
51     0                   280349    280349   280349   280349    280349
53     0                       11        11       11       11        11

                   rule_apply  outlier  valor_un_ref
codigo has_change
1      0                   90       90            90
11     0              2258621  2258621       2258621
12     0               261493   261493        261493
13     0                13398    13398         13398
14     0              1846912  1846912       1846912
15     0               360352   360352        360352
16     0               119340   119340        119340
17     0                23776    23776         23776
18     0                14173    14173         14173
21     0                57650    57650         57650
22     0               886284   886284        886284
23     0                11400    11400         11400
31     0               167124   167124        167124
32     0               207373   207373        207373
33     0                 2258     2258          2258
34     0                  734      734           734
41     0               746946   746946        746946
       1               397583   397583        397583
42     0                  391      391           391
51     0               280349   280349        280349
53     0                   11       11            11

[21 rows x 27 columns]