# Rename Tables and columns

In [1]:
import pandas as pd

from glob import glob

# Config

In [2]:
PATH_TABLES = 'data/comparacoes'

FIELDS = [
    'ano', 'item',
    'qt_nova', 'unit_kg',
    'valor_kg', 'price_kg', 
    'valor_novo', 'valor_novo_s'
]

NEW_FIELDS = [
    'ano', 'item', 
    'qt_kg_amostra', 'qt_kg_estimado',
    'valor_un_kg_amostra', 'valor_un_kg_estimado',
    'valor_total_kg_amostra', 'valor_total_kg_estimado'
]

# Rename

In [3]:
d = []
for path in glob(f'{PATH_TABLES}/produto_14*'):
	code = int(path.split('_')[1])
	
	df_comp = pd.read_csv(path)[FIELDS].rename(columns=dict(zip(FIELDS, NEW_FIELDS)))
	df_comp['codigo'] = code

	d.append(df_comp)
	
result = pd.concat(d)

In [4]:
result.to_csv('data/14_table_comparasions.csv')

In [5]:
result

,ano,item,qt_kg_amostra,qt_kg_estimado,valor_un_kg_amostra,valor_un_kg_estimado,valor_total_kg_amostra,valor_total_kg_estimado,codigo
0,2018,"FRANGO, FILE",5.0,5.227273,9.20,8.80,46.00,46.00,14
1,2013,"FRANGO INTEIRO, COM PELE",33.0,32.779633,5.95,5.99,196.35,196.35,14
2,2018,"FRANGO PEITO, COM PELE",70.0,98.187919,10.45,7.45,731.50,731.50,14
3,2019,"FRANGO, PEITO, DIVERSOS CORTES, RESFRIADO/CONG...",35.0,27.250000,6.54,8.40,228.90,228.90,14
4,2016,"FRANGO, PEITO, DIVERSOS CORTES, RESFRIADO/CONG...",54.0,54.000000,6.73,6.73,363.42,363.42,14
...,...,...,...,...,...,...,...,...,...
1319,2015,"FRANGO INTEIRO, RESFRIADO/CONGELADO",354.0,354.000000,7.50,7.50,2655.00,2655.00,14
1320,2019,FILE DE PEITO DE FRANGO,160.0,160.000000,9.35,9.35,1496.00,1496.00,14
1321,2015,"FRANGO, PEITO, DIVERSOS CORTES, RESFRIADO/CONG...",836.0,836.000000,6.47,6.47,5408.92,5408.92,14
1322,2016,"FRANGO INTEIRO, RESFRIADO/CONGELADO",88.0,88.000000,4.79,4.79,421.52,421.52,14
1323,2019,COXA E SOBRECOXA DE FRANGO,40.0,40.000000,8.48,8.48,339.20,339.20,14